In [11]:
# Imports
import pandas as pd
from enum import Enum
import math

In [12]:
# Ranking Method 1 LoL
class Rank_Method_One_LoL(Enum):
    U = -math.inf
    I4 = 50
    I3 = 100
    I2 = 150
    I1 = 200
    B4 = 300
    B3 = 400
    B2 = 500
    B1 = 600
    S4 = 700
    S3 = 800
    S2 = 900
    S1 = 1000
    G4 = 1150
    G3 = 1300
    G2 = 1450
    G1 = 1600
    P4 = 1800
    P3 = 2000
    P2 = 2200
    P1 = 2400
    E4 = 2700
    E3 = 3000
    E2 = 3300
    E1 = 3600
    D4 = 4000
    D3 = 4400
    D2 = 4900
    D1 = 5400
    M = 6000
    GR = 7000
    C = 8500

In [13]:
# Ranking method 2 LoL
class Rank_Method_Two_LoL(Enum):
    U = -math.inf
    I4 = 100
    I3 = 200
    I2 = 300
    I1 = 450
    B4 = 650
    B3 = 850
    B2 = 1100
    B1 = 1400
    S4 = 1750
    S3 = 2100
    S2 = 2450
    S1 = 2800
    G4 = 3150
    G3 = 3500
    G2 = 3850
    G1 = 4200
    P4 = 4550
    P3 = 4900
    P2 = 5250
    P1 = 5600
    E4 = 5950
    E3 = 6300
    E2 = 6650
    E1 = 7000
    D4 = 7350
    D3 = 7700
    D2 = 8050
    D1 = 8400
    M = 8750
    GR = 9100
    C = 9450

In [14]:
# Ranking Method 3 LoL
class Rank_Method_Three_LoL(Enum):
  U = 0
  I4 = 100
  I3 = 200
  I2 = 300
  I1 = 400
  B4 = 500
  B3 = 600
  B2 = 700
  B1 = 800
  S4 = 900
  S3 = 1000
  S2 = 1100
  S1 = 1200
  G4 = 1300
  G3 = 1400
  G2 = 1500
  G1 = 1600
  P4 = 1700
  P3 = 1800
  P2 = 1900
  P1 = 2000
  E4 = 2100
  E3 = 2200
  E2 = 2300
  E1 = 2400
  D4 = 2500
  D3 = 2600
  D2 = 2700
  D1 = 2900
  M = 3000
  GR = 3100
  C = 3200

In [15]:
def convert_rank(rank_str):
    try:
        return Rank[rank_str].value
    except KeyError:
        return 0  # Default value if the string is not found in the Enum

def calculate_metrics(group):
    top5_ranks = group.nlargest(5, 'Rank')['Rank'].reset_index(drop=True)
    average_rank = top5_ranks.mean()
    if len(top5_ranks) == 5:
        difference = top5_ranks.iloc[0] - top5_ranks.iloc[-1]
    else:
        difference = 0  # Default difference if there are not enough players to calculate
    return pd.Series([average_rank, difference], index=['Average', 'Difference'])

def average_top5player_teams_with_metrics(df):
    # Convert the 'Rank' column to integer values
    df['Rank'] = df['Rank'].map(convert_rank)

    # Group by Team and calculate the metrics
    result_df = df.groupby('Team').apply(calculate_metrics).reset_index()

    # Sort the DataFrame by the 'Average' column
    result_df = result_df.sort_values(by='Average', ascending=False)

    return result_df

In [16]:
# Load and prepare the DataFrame
df = pd.read_excel('TeamsOutputSheet.xlsx')
result_df = average_top5player_teams_with_metrics(df)
print(result_df)

# Output Results
result_df.to_excel('TeamRankMetricsOutput.xlsx', index=False)

                         Team  Average  Difference
28   Zephyr Loch Ness Monster   8680.0       350.0
10          Grizzled Gamblers   8540.0       700.0
18              Lars de Vries   8470.0      1050.0
2                  Blitzfrank   8190.0      1400.0
7           Duivelsei Academy   8120.0      2100.0
9              Green Tea Love   7910.0      1050.0
8         Esports Team Twente   7700.0      2450.0
27              Zephyr Kratos   7210.0      4200.0
20       Peritan the Platypus   7210.0      1400.0
17           Iron Bucket Boys   7140.0      2450.0
25               Zephyr Hydra   6860.0      1050.0
22           TSEA Link Reborn   6860.0      3850.0
31               Zephyr Shiva   6720.0      1050.0
29            Zephyr Odysseus   6650.0      3850.0
19                 Padvinders   6580.0      2100.0
13              Ignite Orange   6580.0      1750.0
6        Dirty Little Animals   6440.0      2450.0
30           Zephyr Ouroboros   6090.0       350.0
1                  BS Scaling   6090.0      3500.0
0               BS Happy Hour   5670.0      1750.0
5            DEI 4Fun Boomers   5530.0      3150.0
23            TSEA Pink Wards   5250.0      2100.0
12               Ignite Green   5180.0      2100.0
26            Zephyr Kerberos   4830.0      2450.0
3            Boosted Chickens   4760.0      1750.0
16           Infinite Spirits   4760.0      4900.0
24                    WDATCKG   4200.0      1400.0
4             Boosted Kittens   3360.0      2100.0
14              Ignite Purple   1890.0      3900.0
11             Ignite Diamond   1670.0      2500.0
15            Infinite Pixels   1520.0      3200.0
21  TSEA Link Happy Dumplings   1520.0      1600.0